pulls:
  # Number of days of inactivity before a PR becomes stale
  daysUntilStale: 1
  # Number of days of inactivity before a stale PR is closed
  daysUntilClose: 7
  # PRs with these labels will never be considered stale
  exemptLabels:
    - Error
    - Keep
  # Label to use when marking an issue as stale
  staleLabel: Stale
  # Comment to post when marking an issue as stale. Set to `false` to disable
  markComment: >
    This pull request has been awaiting review for 24 hours. If you are a reviewer, please
    complete your review as soon as possible. If you are unable to do so, please find someone
    else to cover for you! If this should be kept open for other reason, assign the label `Keep`
    and stale won't comment on it again. Otherwise in a week this candidate review will be closed.
  # Comment to post when closing a stale issue. Set to `false` to disable
  closeComment: false
